# Generated by Django 5.2.13 on 2026-04-10 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CareWorker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="이름")),
                ("phone", models.CharField(max_length=20, verbose_name="연락처")),
                ("region", models.CharField(max_length=100, verbose_name="담당 지역")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="활성 여부"),
                ),
            ],
            options={
                "verbose_name": "돌봄관리사",
                "verbose_name_plural": "돌봄관리사",
                "db_table": "care_workers",
            },
        ),
        migrations.CreateModel(
            name="Elder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="이름")),
                ("age", models.IntegerField(verbose_name="나이")),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "남성"), ("F", "여성")],
                        max_length=1,
                        verbose_name="성별",
                    ),
                ),
                ("address", models.TextField(verbose_name="주소")),
                (
                    "lat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        max_digits=10,
                        null=True,
                        verbose_name="위도",
                    ),
                ),
                (
                    "lng",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        max_digits=10,
                        null=True,
                        verbose_name="경도",
                    ),
                ),
                (
                    "region_code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=20,
                        verbose_name="지역코드",
                    ),
                ),
                (
                    "diseases",
                    models.JSONField(
                        blank=True, default=list, verbose_name="질환 목록"
                    ),
                ),
                (
                    "disease_count",
                    models.IntegerField(default=0, verbose_name="질환 수"),
                ),
                (
                    "bmi",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="BMI",
                    ),
                ),
                (
                    "health_grade",
                    models.CharField(
                        choices=[("양호", "양호"), ("주의", "주의"), ("위험", "위험")],
                        default="양호",
                        max_length=10,
                        verbose_name="건강등급",
                    ),
                ),
                (
                    "medications",
                    models.JSONField(
                        blank=True, default=list, verbose_name="복용약 목록"
                    ),
                ),
                (
                    "recent_hospital",
                    models.BooleanField(default=False, verbose_name="최근 입원 여부"),
                ),
                (
                    "housing_type",
                    models.CharField(
                        choices=[
                            ("아파트", "아파트"),
                            ("단독주택", "단독주택"),
                            ("다세대", "다세대"),
                            ("연립", "연립"),
                            ("기타", "기타"),
                        ],
                        default="단독주택",
                        max_length=20,
                        verbose_name="주택유형",
                    ),
                ),
                (
                    "building_year",
                    models.IntegerField(blank=True, null=True, verbose_name="건축년도"),
                ),
                (
                    "has_cooling",
                    models.BooleanField(default=False, verbose_name="냉방장치"),
                ),
                (
                    "has_heating",
                    models.BooleanField(default=True, verbose_name="난방장치"),
                ),
                (
                    "flood_risk",
                    models.BooleanField(default=False, verbose_name="침수위험지역"),
                ),
                (
                    "lives_alone",
                    models.BooleanField(default=True, verbose_name="독거 여부"),
                ),
                (
                    "has_guardian",
                    models.BooleanField(default=False, verbose_name="보호자 유무"),
                ),
                (
                    "guardian_phone",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        verbose_name="보호자 연락처",
                    ),
                ),
                (
                    "care_visit_freq",
                    models.CharField(
                        blank=True,
                        default="주1회",
                        max_length=20,
                        verbose_name="돌봄 방문 주기",
                    ),
                ),
                (
                    "isolation_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="고립도 점수",
                    ),
                ),
                (
                    "last_contact",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="마지막 연락일"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="삭제 여부"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "care_worker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="elders",
                        to="elders.careworker",
                        verbose_name="담당 돌봄관리사",
                    ),
                ),
            ],
            options={
                "verbose_name": "대상자",
                "verbose_name_plural": "대상자",
                "db_table": "elders",
                "indexes": [
                    models.Index(fields=["region_code"], name="idx_elder_region")
                ],
            },
        ),
    ]
