# Generated by Django 5.2.13 on 2026-04-10 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("elders", "0001_initial"),
        ("risk", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("안부전화", "안부전화"),
                            ("방문배정", "방문배정"),
                            ("긴급출동", "긴급출동"),
                            ("보호자알림", "보호자알림"),
                        ],
                        max_length=20,
                        verbose_name="알림 유형",
                    ),
                ),
                (
                    "alert_level",
                    models.CharField(
                        choices=[("주의", "주의"), ("경계", "경계"), ("심각", "심각")],
                        max_length=10,
                        verbose_name="알림 등급",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("발송됨", "발송됨"),
                            ("응답완료", "응답완료"),
                            ("미응답", "미응답"),
                        ],
                        default="발송됨",
                        max_length=10,
                        verbose_name="상태",
                    ),
                ),
                ("note", models.TextField(blank=True, default="", verbose_name="비고")),
                (
                    "sent_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="발송 시각"),
                ),
                (
                    "responded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="응답 시각"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "elder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="elders.elder",
                        verbose_name="대상자",
                    ),
                ),
                (
                    "risk_score",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alerts",
                        to="risk.riskscore",
                        verbose_name="위험도 평가",
                    ),
                ),
            ],
            options={
                "verbose_name": "알림",
                "verbose_name_plural": "알림",
                "db_table": "alerts",
                "indexes": [
                    models.Index(
                        fields=["elder", "-created_at"], name="idx_alert_elder_created"
                    ),
                    models.Index(fields=["status"], name="idx_alert_status"),
                ],
            },
        ),
    ]
