# Generated by Django 5.2.13 on 2026-04-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeatherAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("폭염", "폭염"),
                            ("한파", "한파"),
                            ("호우", "호우"),
                            ("강풍", "강풍"),
                            ("대설", "대설"),
                            ("풍랑", "풍랑"),
                            ("기타", "기타"),
                        ],
                        max_length=20,
                        verbose_name="특보 유형",
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        default="충남 청양군", max_length=100, verbose_name="지역"
                    ),
                ),
                ("issued_at", models.DateTimeField(verbose_name="발효 시각")),
                (
                    "effective_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="종료 시각"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
            ],
            options={
                "verbose_name": "기상 특보",
                "verbose_name_plural": "기상 특보",
                "db_table": "weather_alerts",
            },
        ),
        migrations.CreateModel(
            name="WeatherForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("forecast_at", models.DateTimeField(verbose_name="예보 시각")),
                (
                    "temperature",
                    models.DecimalField(
                        decimal_places=1, max_digits=5, verbose_name="예보 기온(℃)"
                    ),
                ),
                (
                    "humidity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="예보 습도(%)",
                    ),
                ),
                (
                    "precipitation_prob",
                    models.IntegerField(default=0, verbose_name="강수확률(%)"),
                ),
                (
                    "sky_condition",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="하늘상태"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
            ],
            options={
                "verbose_name": "기상 예보",
                "verbose_name_plural": "기상 예보",
                "db_table": "weather_forecasts",
            },
        ),
        migrations.CreateModel(
            name="WeatherObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "station_id",
                    models.CharField(
                        default="238", max_length=10, verbose_name="관측소 ID"
                    ),
                ),
                (
                    "station_name",
                    models.CharField(
                        default="청양", max_length=50, verbose_name="관측소명"
                    ),
                ),
                ("observed_at", models.DateTimeField(verbose_name="관측 시각")),
                (
                    "temperature",
                    models.DecimalField(
                        decimal_places=1, max_digits=5, verbose_name="기온(℃)"
                    ),
                ),
                (
                    "feels_like",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="체감온도(℃)",
                    ),
                ),
                (
                    "humidity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="습도(%)",
                    ),
                ),
                (
                    "wind_speed",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="풍속(m/s)",
                    ),
                ),
                (
                    "precipitation",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        max_digits=7,
                        verbose_name="강수량(mm)",
                    ),
                ),
                (
                    "pm25",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=6,
                        null=True,
                        verbose_name="PM2.5(㎍/㎥)",
                    ),
                ),
                (
                    "pm25_grade",
                    models.CharField(
                        blank=True, default="", max_length=10, verbose_name="PM2.5 등급"
                    ),
                ),
                (
                    "pm10",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=6,
                        null=True,
                        verbose_name="PM10(㎍/㎥)",
                    ),
                ),
                (
                    "ozone",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=6,
                        null=True,
                        verbose_name="오존(ppm)",
                    ),
                ),
                (
                    "weather_alert",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="기상특보"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
            ],
            options={
                "verbose_name": "기상 관측",
                "verbose_name_plural": "기상 관측",
                "db_table": "weather_observations",
                "indexes": [
                    models.Index(fields=["-observed_at"], name="idx_weather_obs_at")
                ],
            },
        ),
    ]
