# Generated by Django 5.2.13 on 2026-04-10 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("elders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RiskScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scored_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="평가 시각"),
                ),
                (
                    "weather_risk",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="기상 위험도",
                    ),
                ),
                (
                    "health_risk",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="건강 위험도",
                    ),
                ),
                (
                    "housing_risk",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="주거 위험도",
                    ),
                ),
                (
                    "isolation_risk",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="고립 위험도",
                    ),
                ),
                (
                    "total_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="종합 점수",
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("관심", "관심"),
                            ("주의", "주의"),
                            ("경계", "경계"),
                            ("심각", "심각"),
                        ],
                        default="관심",
                        max_length=10,
                        verbose_name="위험 등급",
                    ),
                ),
                (
                    "model_version",
                    models.CharField(
                        default="rule-v1.0", max_length=20, verbose_name="모델 버전"
                    ),
                ),
                (
                    "feature_importance",
                    models.JSONField(blank=True, default=dict, verbose_name="기여도"),
                ),
                (
                    "elder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_scores",
                        to="elders.elder",
                        verbose_name="대상자",
                    ),
                ),
            ],
            options={
                "verbose_name": "위험도 평가",
                "verbose_name_plural": "위험도 평가",
                "db_table": "risk_scores",
                "indexes": [
                    models.Index(
                        fields=["elder", "-scored_at"], name="idx_risk_elder_scored"
                    ),
                    models.Index(fields=["risk_level"], name="idx_risk_level"),
                ],
            },
        ),
    ]
